### ISSUE TITLE
First attempt with starting app always fails

### ISSUE THREAD

**Issue by tim77** [flathub/com.google.Chrome#10] opened 2020-08-23 13:26 UTC
Every first cold start Chrome fails. App start itself, but all tabs spinning and can't load any old or new web page. After restarting Chrome it works fine.

Also almost every time need to re-authorize in Google account, but maybe we should handle this in separate issue?

Please tell how i can provide more info and details about such issues to help with debugging?

**Edit:** not every first cold start, i would say this happens randomly.

Distro: `Fedora 32`
Flatpak: `1.8.2`
xdg-desktop-portal: `1.7.2`

**Comment by tinywrkb** [comment] 2020-08-24 12:46
Your Flatpak version is out-of-date. Update to 1.8.2 which fixes this issue.

**Comment by tinywrkb** [comment] 2020-08-24 14:17
Because you didn't give any detail about the packages versions and [this](https://github.com/flathub/com.google.Chrome/issues/3) was recently closed.

**Comment by refi64** [comment] 2020-08-24 20:12
Can you start it from the command line with `--env=ZYPAK_DEBUG=1` and post the output, in particular looking for any errors? I should probably have zypak log to the journal regardless...

**Comment by asegarra** [comment] 2020-08-25 19:01
I'm getting this as well, when I restart Chrome I have to sign in again. Here is the output with --env=ZYPAK_DEBUG=1

`flatpak run com.google.Chrome -env=ZYPAK_DEBUG=1
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/extra/chrome --type=zygote
LaunchProcess: failed to execvp:
/app/extra/nacl_helper
[13:13:0825/145903.639140:ERROR:nacl_fork_delegate_linux.cc(323)] Bad NaCl helper startup ack (0 bytes)
Stub sandbox ignoring command: /app/extra/nacl_helper
[1:2:0825/145903.644073:ERROR:nacl_fork_delegate_linux.cc(323)] Bad NaCl helper startup ack (0 bytes)
Gtk-Message: 14:59:03.737: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:59:03.737: Failed to load module "canberra-gtk-module"
[2:31:0825/145903.744566:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[42:42:0825/145903.833568:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[2:43:0825/145903.913380:ERROR:token_service_table.cc(140)] Failed to decrypt token for service AccountId-101099092825277203944
[2:27:0825/145903.930431:ERROR:nacl_browser.cc(309)] Failed to open NaCl IRT file "/app/extra/nacl_irt_x86_64.nexe": -4
[2:137:0825/145904.058792:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:137:0825/145904.058825:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:137:0825/145904.058861:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:137:0825/145904.058884:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:137:0825/145904.058907:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:74:0825/145912.620895:ERROR:gcm_store_impl.cc(941)] Failed to restore security token.
`

**Comment by asegarra** [comment] 2020-08-25 19:09
Don't know if this is related, but I see something similar to #9 about crytpo

```
[2:43:0825/145903.913380:ERROR:token_service_table.cc(140)] Failed to decrypt token for service AccountId-101099092825277203944
```

**Comment by refi64** [comment] 2020-08-29 02:10
The re-authorizing is likely #9, which is a separate issue. For this one, my hands are largely tied unless I can some debug logs since for some reason I can't reproduce this at all...

**Comment by refi64** [comment] 2020-08-29 02:13
Actually the second I posted that, I opened the program and suddenly I could reproduce this :sweat_smile:

**Comment by tim77** [comment] 2020-08-29 02:20
@refi64 sorry for delay here, yep, with `--env=ZYPAK_DEBUG=1` i have same errors when this issue happens:
`Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`

**Comment by refi64** [comment] 2020-08-29 02:27
That error is normal and should be ignored, I was more hoping for the rest of the debug logging.

**Comment by refi64** [comment] 2021-04-07 01:12
This should have been fixed by the recent secret portal downgrade, please let me know if it still occurs.

**Closed by refi64** 2021-04-07 01:12 UTC
